responder_pregunta_overseer:
  description: >
    Recibe una pregunta: "{topic}" y responde bas치ndose en su conocimiento.
    Si no tiene suficiente informaci칩n, debe consultar sus herramientas antes de responder.
    Debe hacer una sola acci칩n a la vez: usar una herramienta o generar la respuesta final.
  expected_output: >
    Respuesta final del overseer basada en toda la informaci칩n recopilada.
  agent: overseer
