seleccion_agente:
  description: >
    Según la pregunta: "{topic}", tienes que preguntar a los agentes para obtener la información necesaria.
    Elige al agente más adecuado para la tarea.
    Recuerda la especialidad de cada agente para luego asignarle la tarea correspondiente.
  expected_output: >
  agent: overseer

responder_pregunta:
  description: >
    Responde la pregunta: "{topic}" con la información que obtuviste del agente.
    Asegúrate de ser claro y conciso en tu respuesta.
  expected_output: >
    Respuesta clara y concisa a la pregunta planteada.
  agent: overseer

obtener_informacion_cofeewatch:
  description: >
    Obtienes información relevante para responder la pregunta: "{topic}", basandote exclusivamente en la información
    que tienes. Si no puedes responder la pregunta, debes decir que no tienes información.
    Luego, envía la información obtenida de vuelta a quien te la solicitó.
  expected_output: >
    Información relevante para responder la pregunta planteada, enviada de vuelta al solicitante.
  agent: cofeewatch

  obtener_informacion_classflow:
  description: >
    Obtienes información relevante para responder la pregunta: "{topic}", basandote exclusivamente en la información
    que tienes. Si no puedes responder la pregunta, debes decir que no tienes información.
    Luego, envía la información obtenida de vuelta a quien te la solicitó.
  expected_output: >
    Información relevante para responder la pregunta planteada, enviada de vuelta al solicitante.
  agent: classflow

responder_pregunta_overseer:
  description: >
    Responde la pregunta: "{topic}" con la información que obtuviste del agente.
    Asegúrate de ser claro y conciso en tu respuesta.
  expected_output: >
    Respuesta clara y concisa a la pregunta planteada.
  agent: overseer